common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 1                            # LiDAR类型标识符
                   # 1表示LiDAR为LIDAR设备（如LiDAR1号）
                   # 2表示LiDAR为V5-LiDAR设备（如LiDAR2号）
                   # 3表示LiDAR为Ouster设备
    scan_line: 6                             # 扫描行数
    blind: 4                                  # 盲线数量

# 映射配置

mapping:
    acc_cov: 0.1                            # 加速度计协方差矩阵值
    gyr_cov: 0.1                            # 陀螺仪协方差矩阵值
    b_acc_cov: 0.0001                        # 偏置加速度计协方差矩阵值
    b_gyr_cov: 0.0001                        # 偏置陀螺仪协方差矩阵值
    fov_degree: 90.0                         # 场景视场角（度）
    det_range: 450.0                         # 检测距离范围（米）
    extrinsic_est_en: false                  # 启用IMU-LiDAR外参数在线估计功能
                   # 目前已关闭
    extrinsic_T: [0.04165, 0.02326, -0.0284]   # IMU到LiDAR的外参数偏移向量（米）
    extrinsic_R: [
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]
    ]                          # IMU到LiDAR的旋转矩阵
publish:
    path_en: false                            # 启用或关闭路径生成
    scan_publish_en: true                     # 输出点云扫描在体 frames中？或者关闭？
    dense_publish_en: true                    # 在全局 frame中使用高密度点云
    scan_bodyframe_pub_en: true              # 输出点云在IMU-Body frame

pcd_save:
    pcd_save_en: true                        # 启用PCD文件保存功能
    interval: -1                            # 每个LiDAR帧的数量；-1表示所有帧合并成一个PCD，可能导致内存占用过高。
