common:
    lid_topic:  "/livox/lidar"       # Livox LiDAR数据的主题名称
    imu_topic:  "/livox/imu"         # IMU主题：IMU数据传输的主题名称
    time_sync_en: false              # 时间同步功能开关：false表示除非确实无法外部时间同步，否则不启用此功能
    time_offset_lidar_to_imu: 0.0   # LiDAR到IMU的时间偏移量：通过其他算法（如LI-Init）校准的时间差值。即使未开启时间同步功能，该参数仍有效。若时间偏移未知，请设为0.0

preprocess:
    lidar_type: 1                   # LiDAR类型：1表示Livox系列LiDAR，2表示Velodyne LiDAR，3表示Ouster LiDAR
    scan_line: 6                    # 扫描线数：设置LiDAR的扫描线条数量为6条
    blind: 4                        # 盲区处理：盲区参数设为4

mapping:
    acc_cov: 0.1                    # 加速度噪声协方差：LiDAR和IMU数据融合中加速度测量的不确定性，值设为0.1
    gyr_cov: 0.1                    # 角速度噪声协方差：LiDAR和IMU数据融合中角速度测量的不确定性，值设为0.1
    b_acc_cov: 0.0001               # 加速度偏置协方差：IMU加速度计的零点漂移不确定性的协方差，设为0.0001
    b_gyr_cov: 0.0001               # 角速度偏置协方差：IMU角速率计的零点漂移不确定性的协方差，设为0.1e-4（即0.0001）
    fov_degree: 100                 # 视场角度：LiDAR扫描的最大视角为100度
    det_range: 260.0                # 检测范围：LiDAR点云数据的有效检测距离，设为260.0米
    extrinsic_est_en: true          # 外参估计功能开关：true表示启用在线计算IMU与LiDAR之间的外参数估计
    extrinsic_T: [ 0.05512, 0.02226, -0.0297 ]   # 外部平移矩阵T：通过校准得到的IMU与LiDAR间的相对位置偏移量，具体数值为[0.05512, 0.02226, -0.0297]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]        # 外部旋转矩阵R：IMU与LiDAR间的相对旋转关系，此处设为单位矩阵，表示两者坐标系一致

publish:
    path_en: false                  # 轨迹发布功能开关：false表示不发布轨迹数据
    scan_publish_en: true           # 扫描点云发布功能开关：true表示启用IMU惯性参考系下的点云扫描输出
    dense_publish_en: true          # 密集点云发布功能开关：true表示以全局坐标系发布高密度点云，false会减少点云数量
    scan_bodyframe_pub_en: true     # 扫描体架发布功能开关：true表示发布IMU惯性参考系下的扫描点云

pcd_save:
    pcd_save_en: true               # PCD文件保存功能开关：true表示启用LiDAR数据的PCD格式保存
    interval: -1                    # 每个PCD文件保存的数据帧数：-1表示将所有帧保存到一个PCD文件中，可能在数据量过大时导致内存溢出，请谨慎使用
