common:  # 通用参数
    ########################################################################
    # lid_topic:  "/points_raw"  # demo01_velodyne.bag
    # imu_topic:  "/imu_raw"
    ########################################################################
    # Recore Stereo Por data:
    # rosbag record -O my_data.bag /xv_sdk/xv_dev/tof_camera/point_cloud /xv_sdk/xv_dev/imu_sensor/data_raw /xv_sdk/xv_dev/sgbm_camera/point_cloud
    lid_topic:  "/xv_sdk/xv_dev/tof_camera/point_cloud"  # tof data
    # lid_topic:  "/xv_sdk/xv_dev/sgbm_camera/point_cloud"  # sgbm data
    imu_topic:  "/xv_sdk/xv_dev/imu_sensor/data_raw"
    ########################################################################
    # lid_topic:  "/kinect2/sd/points"    # gazebo.bag
    # imu_topic:  "/imu/data"
    ########################################################################
    time_sync_en: false           # 是否启用 LiDAR 和 IMU 的时间同步 # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # LiDAR 和 IMU 之间的固定时间偏移（单位：秒），用于手动校准时间差 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:  # LiDAR 预处理参数
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 1
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 2            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 2

mapping:
    acc_cov: 0.1                  # 加速度噪声协方差：LiDAR和IMU数据融合中加速度测量的不确定性，值设为0.1
    gyr_cov: 0.1                  # 角速度噪声协方差：LiDAR和IMU数据融合中角速度测量的不确定性，值设为0.1
    b_acc_cov: 0.0001             # 加速度偏置协方差：IMU加速度计的零点漂移不确定性的协方差，设为0.0001
    b_gyr_cov: 0.0001             # 角速度偏置协方差：IMU角速率计的零点漂移不确定性的协方差，设为0.1e-4（即0.0001）
    fov_degree:    64.3           # 视场角度：LiDAR扫描的最大视角为180度
    det_range:     5.0          # 检测范围：LiDAR点云数据的有效检测距离，设为100.0米
    extrinsic_est_en:  false      # 外参估计功能开关：true表示启用在线计算IMU与LiDAR之间的外参数估计 # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [ 0.0106124, 0.000245367, 0.00660701]    # 外部平移矩阵T：通过校准得到的IMU与LiDAR间的相对位置偏移量
    extrinsic_R: [ 0.99999, 0.00119637, -0.00426322, 
                   -0.00125588, 0.999901, -0.0139822, 
                   0.00424608, 0.0139874, 0.999893]       # 外部旋转矩阵R：IMU与LiDAR间的相对旋转关系，此处设为单位矩阵，表示两者坐标系一致

publish:
    path_en:  false              # 轨迹发布功能开关：false表示不发布轨迹数据
    scan_publish_en:  true       # 扫描点云发布功能开关：true表示启用IMU惯性参考系下的点云扫描输出 # false: close all the point cloud output
    dense_publish_en: true       # 密集点云发布功能开关：true表示以全局坐标系发布高密度点云，false会减少点云数量 # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # 扫描体架发布功能开关：true表示发布IMU惯性参考系下的扫描点云 # true: output the point cloud scans in IMU-body-frame

pcd_save:  # pcd_save 部分设置点云保存参数
    pcd_save_en: true            # pcd_save_en: true 启用点云保存功能 
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # interval: -1 设置保存间隔，-1 表示所有扫描帧保存到一个 PCD 文件中（可能会导致内存占用过高） # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
