left_arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pitch_l_joint
    - shoulder_roll_l_joint
    - shoulder_yaw_l_joint
    - elbow_pitch_l_joint
    - elbow_yaw_l_joint
    - wrist_pitch_l_joint
    - wrist_roll_l_joint
  gains:
    shoulder_pitch_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_roll_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_yaw_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_pitch_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_yaw_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pitch_r_joint
    - shoulder_roll_r_joint
    - shoulder_yaw_r_joint
    - elbow_pitch_r_joint
    - elbow_yaw_r_joint
    - wrist_pitch_r_joint
    - wrist_roll_r_joint
  gains:
    shoulder_pitch_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_roll_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_yaw_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_pitch_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_yaw_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
dual_arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pitch_l_joint
    - shoulder_roll_l_joint
    - shoulder_yaw_l_joint
    - elbow_pitch_l_joint
    - elbow_yaw_l_joint
    - wrist_pitch_l_joint
    - wrist_roll_l_joint
    - shoulder_pitch_r_joint
    - shoulder_roll_r_joint
    - shoulder_yaw_r_joint
    - elbow_pitch_r_joint
    - elbow_yaw_r_joint
    - wrist_pitch_r_joint
    - wrist_roll_r_joint
  gains:
    shoulder_pitch_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_roll_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_yaw_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_pitch_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_yaw_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_pitch_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_roll_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_yaw_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_pitch_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_yaw_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1