controller_list:
  - name: left_arm_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_pitch_l_joint
      - shoulder_roll_l_joint
      - shoulder_yaw_l_joint
      - elbow_pitch_l_joint
      - elbow_yaw_l_joint
      - wrist_pitch_l_joint
      - wrist_roll_l_joint
  - name: right_arm_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_pitch_r_joint
      - shoulder_roll_r_joint
      - shoulder_yaw_r_joint
      - elbow_pitch_r_joint
      - elbow_yaw_r_joint
      - wrist_pitch_r_joint
      - wrist_roll_r_joint
  - name: dual_arm_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_pitch_l_joint
      - shoulder_roll_l_joint
      - shoulder_yaw_l_joint
      - elbow_pitch_l_joint
      - elbow_yaw_l_joint
      - wrist_pitch_l_joint
      - wrist_roll_l_joint
      - shoulder_pitch_r_joint
      - shoulder_roll_r_joint
      - shoulder_yaw_r_joint
      - elbow_pitch_r_joint
      - elbow_yaw_r_joint
      - wrist_pitch_r_joint
      - wrist_roll_r_joint